name = "sitemap"
main = "dist/index.js"
account_id = "5c5263e05bb1e54242b1afb12a5c9259"

routes = [
  { pattern = "mytiki.com/sitemap.xml", zone_id = "7be31970110fa56b1f8e1fe915a8b938" }
]

compatibility_date = "2022-09-12"

[vars]
HOST = "https://cdn.mytiki.com/assets/sitemap.xml"
