name: hello_tiki_module
description: Flutter Module to Hello TIKI library.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hello_tiki_plugin:
    path: ../hello_tiki_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.hello_tiki_module
    iosBundleIdentifier: com.example.hello_tiki_module
